import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import CenterComponent from "@/components/CenterComponent";
import Footer from "@/components/Footer";
import LandingPage from "@/components/LandingPage";
import bgImg from "../../public/bgImg.svg"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[url('../../public/bgImg.svg')]  bg-cover bg-no-repeat">
      <body className={inter.className}>
      <Header/>
      {children}
      <CenterComponent />
      <LandingPage/>
      <Footer/>
      </body>
    </html>
  );
}
