import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import CenterComponent from "@/components/CenterComponent";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[url('../../public/webBack.svg')]">
      <body className={inter.className}>{children} 
      
      <Header/>
      <CenterComponent />
      <Footer/>
      </body>
    </html>
  );
}
